"""Draw the batching figures from measurements that already happened.

Reads `results/batch_profiles.json` and `results/decode_sweep.json` and writes three
figures. It measures nothing, for the same reason `plot_decode_profiles.py` measures
nothing: a run repeated after a pause reproduces within a few percent and back to back
drifts further, so a figure regenerated by re-measuring would disagree with the tables
beside it for reasons that have nothing to do with the code.

Writes, into `docs/img/`:

  batch_scaling.png   speedup against batch width per cache occupancy, and measured
                      against what the cost split predicts
  alternation.png     one schedule over time: tokens stop coming out while a prefill
                      chunk runs, at two settings of the alternation knob
  decode_sweep.png    latency percentiles, attainment and goodput against offered load

Three encodings, three jobs
---------------------------

Precision is an identity, so it keeps the categorical hues and markers the four
existing decoder figures use, imported from `plot_decode_profiles.py` rather than
restated here.

Cache occupancy is a magnitude, so it gets a sequential ramp of one hue rather than
three more categorical colours: 128, 512 and 960 cached tokens are ordered, and three
unrelated hues would throw that ordering away. The violet ramp is deliberately not the
precision blue, so a reader cannot carry "blue means fp32" into a panel where blue
means "512 tokens". Every step is at least 3:1 against white (3.29, 6.22, 12.3) and
monotone in OKLab lightness (0.657, 0.508, 0.342), which is what makes it a ramp
rather than three colours in a row.

A scheduling policy is an identity too, and it takes the colours the encoder lane's
load sweep already uses for the same job -- the red-brown for the baseline everything
is compared against, blue for the policy under test -- with green added for the third.
That palette passes the contrast and colour-deficiency checks on every pair, except
that the green sits below 3:1 against white, which is why every line here is also
labelled at its end.

Usage:
    python scripts/plot_batching.py
    python scripts/plot_batching.py --batch-profiles results/batch_profiles.json \
        --output-dir /tmp/figures
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# The house style, defined once. `_label_ends` in particular solves a problem worth
# not solving twice: two series ending a few percent apart print their labels on top
# of each other, which is the one way a direct label is worse than none.
from plot_decode_profiles import (  # noqa: E402
    GRID,
    INK,
    INK_MUTED,
    SERIES_COLOURS,
    SERIES_MARKERS,
    _label_ends,
    _save,
    _style,
)

from anytime_serving.utils.logger import get_logger  # noqa: E402

LOGGER = get_logger("scripts.plot_batching")

# Sequential, light to dark, for cache occupancy. See the module docstring for the
# contrast and lightness figures these were chosen against.
OCCUPANCY_RAMP = ("#9b7fd4", "#6f4bb8", "#3f2472")
# Categorical, for scheduling policy. The baseline keeps the colour the encoder lane's
# load sweep gives the policy it compares against.
POLICY_COLOURS = ("#b2432f", "#2f6fb2", "#1baf7a")
POLICY_MARKERS = ("o", "s", "^")
# Prefill intervals in the timeline. A wash rather than a series: it is the cause of
# the stall, not a second measurement competing with the line.
BAND = "#efe9d9"


def _occupancy_colours(lengths: list[int]) -> dict[int, str]:
    """Assign the ramp shortest to longest, so darker always means more cache.

    Assigned by rank rather than by value, so a sweep at different lengths still reads
    in order. More than three lengths would need more steps: the ramp is extended by
    repeating its darkest step rather than by inventing hues, which is visible as two
    lines the same colour and is meant to be.
    """
    ordered = sorted(set(lengths))
    return {
        length: OCCUPANCY_RAMP[min(index, len(OCCUPANCY_RAMP) - 1)]
        for index, length in enumerate(ordered)
    }


def _batch_positions(widths: list[int]) -> tuple[list[int], list[str]]:
    """Batch widths on a categorical axis.

    1, 2, 4, 8, 16, 32 on a linear axis crushes everything below 8 into the corner, and
    a log axis invites reading the gaps as proportional to something. They are steps in
    a sweep, so they are drawn as steps.
    """
    return list(range(len(widths))), [str(width) for width in widths]


def plot_batch_scaling(data: dict, path: Path) -> None:
    """What batching buys, and whether the cost split explains it.

    One panel per precision so nine series are three sets of three rather than a
    thicket, sharing one y-axis: panels with their own scales would let a 1.3x and a
    2.4x look alike, which is the comparison the figure exists to make.
    """
    import matplotlib.pyplot as plt

    profiles = data["precisions"]
    widths = sorted({point["batch_size"] for p in profiles for point in p["scaling"]})
    lengths = sorted({point["cached_tokens"] for p in profiles for point in p["scaling"]})
    colours = _occupancy_colours(lengths)
    positions, labels = _batch_positions(widths)

    panels = len(profiles) + 1
    columns = 2
    rows = -(-panels // columns)
    figure, grid = plt.subplots(rows, columns, figsize=(11.0, 4.0 * rows), squeeze=False)
    axes = [grid[row][column] for row in range(rows) for column in range(columns)]

    ceiling = max(
        (point["speedup_vs_serial"] for p in profiles for point in p["scaling"]), default=1.0
    )
    for axis, profile in zip(axes, profiles, strict=False):
        ends: list[tuple[float, float, str, str]] = []
        for length in lengths:
            points = sorted(
                (point for point in profile["scaling"] if point["cached_tokens"] == length),
                key=lambda point: point["batch_size"],
            )
            if not points:
                continue
            xs = [positions[widths.index(point["batch_size"])] for point in points]
            ys = [point["speedup_vs_serial"] for point in points]
            axis.plot(
                xs,
                ys,
                marker="o",
                markersize=5,
                linewidth=2,
                color=colours[length],
                label=f"{length} cached",
            )
            ends.append((xs[-1], ys[-1], str(length), colours[length]))
        # Break-even. Above it batching served the batch faster than stepping through
        # it; below it the batch cost more than the steps it replaced.
        axis.axhline(1.0, color=INK_MUTED, linestyle="--", linewidth=1)
        axis.set_xticks(positions, labels)
        axis.set_ylim(0.0, ceiling * 1.18)
        _style(
            axis,
            xlabel="Sequences in the batch",
            ylabel="Tokens per second, against one at a time",
            title=profile["precision"],
        )
        _label_ends(axis, ends)

    axes[0].legend(loc="upper left", fontsize=8, frameon=False)
    axes[0].annotate(
        "break-even",
        xy=(0.02, 1.0),
        xycoords=("axes fraction", "data"),
        xytext=(0, 4),
        textcoords="offset points",
        fontsize=7,
        color=INK_MUTED,
    )

    parity = axes[len(profiles)]
    limit = 1.0
    for profile in profiles:
        precision = profile["precision"]
        xs = [
            point["predicted_speedup"]
            for point in profile["scaling"]
            if point["batch_size"] > 1 and point["predicted_speedup"] > 0
        ]
        ys = [
            point["speedup_vs_serial"]
            for point in profile["scaling"]
            if point["batch_size"] > 1 and point["predicted_speedup"] > 0
        ]
        if not xs:
            continue
        limit = max(limit, max(xs), max(ys))
        parity.scatter(
            xs,
            ys,
            s=26,
            marker=SERIES_MARKERS[precision],
            color=SERIES_COLOURS[precision],
            label=precision,
            zorder=3,
        )
    parity.plot(
        [0, limit * 1.05],
        [0, limit * 1.05],
        color=INK_MUTED,
        linestyle="--",
        linewidth=1,
        zorder=2,
    )
    _style(
        parity,
        xlabel="Predicted by the fitted split",
        ylabel="Measured",
        title="Does the split explain it?",
        label_room=False,
    )
    parity.legend(loc="upper left", fontsize=8, frameon=False)
    # Above the parity line, where there is nothing plotted: every measured point falls
    # below it, which is the panel's finding and also what leaves this space free.
    parity.annotate(
        "on the line, only the cache-independent\nterm amortises, as fitted.\nBelow it, "
        "a batched step costs more\nthan that term explains",
        xy=(0.04, 0.55),
        xycoords="axes fraction",
        fontsize=7.5,
        color=INK_MUTED,
    )

    for axis in axes[panels:]:
        axis.set_visible(False)

    figure.suptitle(
        f"{data['model']}: what batching a decode step buys, measured through the scheduler\n"
        f"{_scaling_sentence(data)}",
        fontsize=11,
        color=INK,
    )
    _save(figure, path, top=0.95 if rows > 1 else 0.86)


def _scaling_sentence(data: dict) -> str:
    """The headline in words, from the widest batch at the two extreme occupancies."""
    profile = data["precisions"][0]
    widest = max(point["batch_size"] for point in profile["scaling"])
    lengths = sorted({point["cached_tokens"] for point in profile["scaling"]})
    at = {}
    for length in (lengths[0], lengths[-1]):
        match = [
            point
            for point in profile["scaling"]
            if point["cached_tokens"] == length and point["batch_size"] == widest
        ]
        if match:
            at[length] = match[0]["speedup_vs_serial"]
    if len(at) < 2:
        return f"{profile['precision']}, batches up to {widest}"
    short, long = lengths[0], lengths[-1]
    return (
        f"{profile['precision']} at batch {widest}: {at[short]:.2f}x with {short} cached "
        f"tokens, {at[long]:.2f}x with {long}"
    )


def plot_alternation(data: dict, path: Path) -> None:
    """One schedule over time: nothing decodes while a prefill chunk runs.

    Cumulative tokens rather than one line per sequence, because the shape of the
    stall is the point and six lines would carry the same shape six times. The bands
    are the prefill chunks, and the line is flat across every one of them by
    construction -- which is the consequence of alternating that the trade-off in
    `batch_scheduler.py` is about.
    """
    import matplotlib.pyplot as plt

    profile = data["precisions"][0]
    traces = profile.get("alternation", [])
    if not traces:
        LOGGER.warning("no alternation trace recorded; skipping %s", path.name)
        return

    figure, grid = plt.subplots(2, len(traces), figsize=(5.6 * len(traces), 7.4), squeeze=False)
    for column, trace in enumerate(traces):
        bands = [
            (step["start_ms"], step["end_ms"])
            for step in trace["steps"]
            if step["kind"] == "prefill"
        ]
        decode = [step for step in trace["steps"] if step["kind"] == "decode"]
        times = [step["end_ms"] for step in decode]
        cumulative: list[int] = []
        total = 0
        for step in decode:
            total += step["batch_size"]
            cumulative.append(total)

        top, bottom = grid[0][column], grid[1][column]
        for axis in (top, bottom):
            for start, end in bands:
                axis.axvspan(start, end, color=BAND, linewidth=0, zorder=1)

        top.plot(
            times,
            cumulative,
            color=SERIES_COLOURS[profile["precision"]],
            linewidth=2,
            zorder=3,
        )
        _style(
            top,
            xlabel="",
            ylabel="Tokens emitted",
            title=(f"{trace['prefill_chunks_per_decode']} prefill chunk(s) between decode steps"),
            label_room=False,
        )
        top.annotate(
            f"longest a decoding sequence went\nwithout a token: "
            f"{trace['max_decode_gap_ms']:.0f} ms\n"
            f"median {trace['decode_gap_p50_ms']:.0f} ms",
            xy=(0.03, 0.72),
            xycoords="axes fraction",
            fontsize=8,
            color=INK_MUTED,
        )

        bottom.step(
            times,
            [step["batch_size"] for step in decode],
            where="post",
            color=SERIES_COLOURS[profile["precision"]],
            linewidth=1.6,
            zorder=3,
        )
        bottom.set_ylim(0, trace["max_batch_size"] + 0.6)
        _style(
            bottom,
            xlabel="Wall time (ms)",
            ylabel="Sequences in the decode step",
            title="",
            label_room=False,
        )

    # One legend entry for the wash, on the first panel only: it means the same thing
    # in all four.
    handle = plt.Rectangle((0, 0), 1, 1, color=BAND)
    grid[0][0].legend(
        [handle],
        ["a prefill chunk is running"],
        loc="lower right",
        fontsize=8,
        frameon=False,
    )

    first = traces[0]
    figure.suptitle(
        f"{data['model']} {profile['precision']}: a prefill chunk and a decode step "
        f"cannot share a run, so they alternate\n"
        f"{first['requests']} generations over one arena, batch width "
        f"{first['max_batch_size']}, prompts of "
        f"{min(first['prompt_tokens'])}-{max(first['prompt_tokens'])} tokens chunked at "
        f"{first['chunk_tokens']}",
        fontsize=11,
        color=INK,
    )
    _save(figure, path, top=0.95)


def plot_decode_sweep(data: dict, path: Path) -> None:
    """Latency, attainment and goodput against offered load, per policy."""
    import matplotlib.pyplot as plt

    rows = data.get("sweep", [])
    if not rows:
        LOGGER.warning("no sweep rows recorded; skipping %s", path.name)
        return
    policies = list(dict.fromkeys(row["policy"] for row in rows))
    colours = {
        policy: POLICY_COLOURS[index % len(POLICY_COLOURS)] for index, policy in enumerate(policies)
    }
    markers = {
        policy: POLICY_MARKERS[index % len(POLICY_MARKERS)] for index, policy in enumerate(policies)
    }

    figure, grid = plt.subplots(2, 2, figsize=(11.5, 8.0))
    # Title, y-label and unit separately: "Goodput (met both targets) (requests/s)"
    # is what happens when the label is built from the title.
    panels = (
        (
            "ttft_p95_ms",
            "Time to first token, p95",
            "Time to first token, p95 (ms)",
            "ms",
            data.get("ttft_slo_ms"),
        ),
        (
            "tpot_p95_ms",
            "Time per output token, p95",
            "Time per output token, p95 (ms)",
            "ms",
            data.get("tpot_slo_ms"),
        ),
        (
            "slo_attainment",
            "Met both targets",
            "Requests meeting both targets (%)",
            "%",
            None,
        ),
        ("goodput_rps", "Goodput (met both targets)", "Goodput (requests/s)", None, None),
    )
    for axis, (column, title, ylabel, unit, threshold) in zip(grid.ravel(), panels, strict=True):
        ends: list[tuple[float, float, str, str]] = []
        for policy in policies:
            series = sorted(
                (row for row in rows if row["policy"] == policy),
                key=lambda row: row["target_utilisation"],
            )
            xs = [row["target_utilisation"] for row in series]
            scale = 100.0 if unit == "%" else 1.0
            ys = [row[column] * scale for row in series]
            axis.plot(
                xs,
                ys,
                marker=markers[policy],
                markersize=5,
                linewidth=2,
                color=colours[policy],
                label=policy,
            )
            ends.append((xs[-1], ys[-1], policy, colours[policy]))
        # Saturation of the capacity load is expressed against.
        axis.axvline(1.0, color=GRID, linestyle=":", linewidth=1.2)
        if threshold:
            axis.axhline(threshold, color=INK_MUTED, linestyle="--", linewidth=1)
            axis.annotate(
                f"target {threshold:.0f} ms",
                xy=(0.02, threshold),
                xycoords=("axes fraction", "data"),
                xytext=(0, 4),
                textcoords="offset points",
                fontsize=7,
                color=INK_MUTED,
            )
        # Log for time to first token, which spans two orders of magnitude once a
        # policy saturates, and linear for everything else. Time per output token moves
        # between about 6 and 27 ms against a 50 ms target, and a log axis there would
        # flatten the difference the panel exists to show.
        if column.startswith("ttft"):
            axis.set_yscale("log")
        _style(
            axis,
            xlabel="Offered load / measured capacity",
            ylabel=ylabel,
            title=title,
        )
        _label_ends(axis, ends)
    grid[0][0].legend(loc="upper left", fontsize=8, frameon=False)

    figure.suptitle(
        f"{data['model']} {data['precision']}: Poisson arrivals against "
        f"{data['capacity_rps']:.2f} requests/s of measured capacity\n"
        f"{data['requests_per_point']} requests per point, "
        f"{data['sweep'][0]['prompt_tokens']}-token prompts, "
        f"{data['sweep'][0]['max_new_tokens']} generated; unloaded reference "
        f"{data['reference_ttft_ms']:.0f} ms to first token, "
        f"{data['reference_tpot_ms']:.1f} ms a token",
        fontsize=11,
        color=INK,
    )
    _save(figure, path, top=0.94)


def _load(path: Path, what: str) -> dict[str, Any] | None:
    if not path.is_file():
        LOGGER.warning("%s is absent, so the %s figure(s) are skipped", path, what)
        return None
    return json.loads(path.read_text())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--batch-profiles",
        type=Path,
        default=Path("results/batch_profiles.json"),
        help="Measurements written by scripts/profile_batching.py",
    )
    parser.add_argument(
        "--decode-sweep",
        type=Path,
        default=Path("results/decode_sweep.json"),
        help="Measurements written by scripts/run_decode_sweep.py",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("docs/img"))
    args = parser.parse_args()

    try:
        import matplotlib
    except ImportError as error:  # pragma: no cover - depends on the environment
        raise SystemExit(
            "matplotlib is required to draw figures. Install it with:\n"
            '    pip install -e ".[bench]"'
        ) from error
    matplotlib.use("Agg")

    mechanism = _load(args.batch_profiles, "batch scaling and alternation")
    sweep = _load(args.decode_sweep, "load sweep")
    if mechanism is None and sweep is None:
        raise SystemExit(
            "nothing to draw. Measure first:\n"
            "    python scripts/profile_batching.py\n"
            "    python scripts/run_decode_sweep.py"
        )

    if mechanism is not None:
        unknown = {p["precision"] for p in mechanism["precisions"]} - set(SERIES_COLOURS)
        if unknown:
            raise SystemExit(
                f"no colour is assigned to {sorted(unknown)}. A precision keeps one "
                f"colour across every figure, so add it to SERIES_COLOURS in "
                f"plot_decode_profiles.py rather than letting matplotlib cycle one."
            )
        plot_batch_scaling(mechanism, args.output_dir / "batch_scaling.png")
        plot_alternation(mechanism, args.output_dir / "alternation.png")
    if sweep is not None:
        plot_decode_sweep(sweep, args.output_dir / "decode_sweep.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
