"""Draw the decoder figures from a measurement that already happened.

Reads `results/decode_profiles.json` and writes the three figures the docs use. It
measures nothing, and that separation is deliberate: whole runs of
`profile_decode.py` reproduce within 2.5% after a pause and drift up to 10% back to
back, so a figure regenerated by re-measuring would disagree with the tables beside
it for reasons that have nothing to do with the code. Rendering from the recorded
JSON means the figure and the table are the same measurement.

Writes, into `docs/img/`:

  decoder_phases.png   TTFT against prompt length, TPOT against cached tokens
  arena_cost.png       what the gather costs, absolutely and as a share of a step
  chunked_prefill.png  TTFT against chunk width, and the logits each width allocates

Three precisions are three series, coloured in a fixed order so a precision keeps its
colour across every panel and figure. Each line is also labelled at its right-hand
end, because one of the three sits below 3:1 contrast against a white surface and
colour alone should not have to carry identity.

Usage:
    python scripts/plot_decode_profiles.py
    python scripts/plot_decode_profiles.py --input results/decode_profiles.json \
        --output-dir /tmp/figures
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from anytime_serving.utils.logger import get_logger

LOGGER = get_logger("scripts.plot_decode_profiles")

# Fixed order, so fp32 is the same colour in every panel. Validated as a set against
# a white surface for deuteranopia, tritanopia and normal vision; the aqua is the one
# below 3:1 contrast, which is why every line carries a direct label as well.
SERIES_COLOURS = {
    "fp32": "#2a78d6",
    "int8": "#eb6834",
    "int4": "#1baf7a",
}
SERIES_MARKERS = {"fp32": "o", "int8": "s", "int4": "^"}
# Chrome sits one shade off the surface rather than competing with the data.
INK = "#0b0b0b"
INK_MUTED = "#52514e"
GRID = "#e1e0d9"
FIGURE_DPI = 150


def _style(axis: Any, *, xlabel: str, ylabel: str, title: str, label_room: bool = True) -> None:
    axis.set_xlabel(xlabel, color=INK_MUTED, fontsize=9)
    axis.set_ylabel(ylabel, color=INK_MUTED, fontsize=9)
    axis.set_title(title, color=INK, fontsize=10)
    axis.grid(True, color=GRID, linewidth=0.8)
    axis.set_axisbelow(True)
    for side in ("top", "right"):
        axis.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        axis.spines[side].set_color(GRID)
    axis.tick_params(colors=INK_MUTED, labelsize=8)
    if label_room:
        # The end-of-line labels are drawn past the last point, so leave them room
        # inside the axes rather than letting them run into the next panel.
        axis.margins(x=0.16)


def _label_ends(axis: Any, entries: list[tuple[float, float, str, str]]) -> None:
    """Name each series at its right-hand end, so colour is not the only cue.

    Called after the data is plotted, because the labels are spread apart in display
    space and that needs the resolved axis limits. Two series ending 7% apart -- fp32
    and int8 routinely do -- otherwise print on top of each other, which is the one
    way a direct label is worse than no label at all.
    """
    if not entries:
        return
    figure = axis.get_figure()
    minimum_gap = 11.0 * figure.dpi / 72.0
    placed: list[tuple[float, float, float, str, str]] = []
    for x, y, text, colour in sorted(entries, key=lambda entry: entry[1]):
        pixels = float(axis.transData.transform((x, y))[1])
        if placed and pixels - placed[-1][1] < minimum_gap:
            pixels = placed[-1][1] + minimum_gap
        placed.append((x, pixels, y, text, colour))
    for x, pixels, y, text, colour in placed:
        original = float(axis.transData.transform((x, y))[1])
        axis.annotate(
            text,
            xy=(x, y),
            xytext=(6, (pixels - original) * 72.0 / figure.dpi),
            textcoords="offset points",
            color=colour,
            fontsize=8,
            va="center",
            annotation_clip=False,
        )


def _default_chunk(profile: dict) -> int:
    """The chunk width the prompt-length sweep ran at, read off the data.

    The profiler sweeps prompt lengths at its default width and then sweeps widths at
    the longest prompt, so any row at a shorter prompt names that default. Hardcoding
    256 here would leave a panel silently empty if the default ever moved.
    """
    longest = max(row["prompt_tokens"] for row in profile["prefill"])
    shorter = [row["chunk_tokens"] for row in profile["prefill"] if row["prompt_tokens"] < longest]
    if shorter:
        return shorter[0]
    widths = Counter(row["chunk_tokens"] for row in profile["prefill"] if row["chunk_tokens"] > 0)
    return min(widths, key=lambda width: (-widths[width], width)) if widths else 0


def _prefill_at(profile: dict, chunk_tokens: int) -> list[dict]:
    rows = [row for row in profile["prefill"] if row["chunk_tokens"] == chunk_tokens]
    return sorted(rows, key=lambda row: row["prompt_tokens"])


def _chunk_sweep(profile: dict, prompt_tokens: int) -> list[dict]:
    """The chunk-width sweep at one prompt length, widest pass first."""
    rows = [row for row in profile["prefill"] if row["prompt_tokens"] == prompt_tokens]
    # chunk_tokens of 0 means one pass, which is the widest of all.
    return sorted(rows, key=lambda row: row["chunk_tokens"] or prompt_tokens, reverse=True)


def plot_phases(data: dict, path: Path) -> None:
    """TTFT and TPOT side by side: the gap between the phases is the point."""
    import matplotlib.pyplot as plt

    figure, (left, right) = plt.subplots(1, 2, figsize=(11.0, 4.2))
    prefill_labels: list[tuple[float, float, str, str]] = []
    decode_labels: list[tuple[float, float, str, str]] = []

    for profile in data["precisions"]:
        precision = profile["precision"]
        colour = SERIES_COLOURS[precision]
        rows = _prefill_at(profile, _default_chunk(profile))
        if rows:
            xs = [row["prompt_tokens"] for row in rows]
            ys = [row["ttft"]["p50_ms"] for row in rows]
            left.plot(
                xs,
                ys,
                marker=SERIES_MARKERS[precision],
                markersize=5,
                linewidth=2,
                color=colour,
                label=precision,
            )
            prefill_labels.append((xs[-1], ys[-1], precision, colour))

        decode = sorted(profile["decode"], key=lambda row: row["cached_tokens"])
        xs = [row["cached_tokens"] for row in decode]
        ys = [row["tpot"]["p50_ms"] for row in decode]
        right.plot(
            xs,
            ys,
            marker=SERIES_MARKERS[precision],
            markersize=5,
            linewidth=2,
            color=colour,
            label=precision,
        )
        decode_labels.append((xs[-1], ys[-1], precision, colour))

    width = _default_chunk(data["precisions"][0])
    # Log scale, because INT4 prefills 4.8x slower than FP32 and on a linear axis it
    # flattens the other two into the baseline. The point of the panel is that all
    # three grow with the prompt, and how far apart they are.
    left.set_yscale("log")
    _style(
        left,
        xlabel="Prompt tokens",
        ylabel="Time to first token (ms, log scale)",
        title=f"Prefill: chunked at {width} tokens",
    )
    _style(
        right,
        xlabel="Cached tokens",
        ylabel="Time per output token (ms)",
        title="Decode: one token against a filled cache",
    )
    left.legend(loc="upper left", fontsize=8, frameon=False)
    _label_ends(left, prefill_labels)
    _label_ends(right, decode_labels)

    fp32 = next(p for p in data["precisions"] if p["precision"] == "fp32")
    cost = fp32["cache_cost"]
    right.annotate(
        f"fp32 fits {cost['decode_base_ms']:.2f} ms + "
        f"{cost['decode_per_token_ms'] * 1000:.2f} us per cached token,\n"
        f"to within {cost['decode_max_residual_ms']:.2f} ms",
        xy=(0.30, 0.06),
        xycoords="axes fraction",
        fontsize=8,
        color=INK_MUTED,
    )

    figure.suptitle(
        f"{data['model']}: prefill and decode are two different measurements\n"
        f"{_gap_sentence(data)}",
        fontsize=11,
        color=INK,
    )
    _save(figure, path, top=0.88)


def _gap_sentence(data: dict) -> str:
    """State the ratio in words, because two panels cannot show it.

    Comparing a bar on one axis against a bar on another is the mistake a dual axis
    makes; the number goes in the title instead.
    """
    fp32 = next(p for p in data["precisions"] if p["precision"] == "fp32")
    prompt = max(row["prompt_tokens"] for row in fp32["prefill"])
    ttft = next(
        row["ttft"]["p50_ms"]
        for row in _prefill_at(fp32, _default_chunk(fp32))
        if row["prompt_tokens"] == prompt
    )
    longest = max(fp32["decode"], key=lambda row: row["cached_tokens"])
    tpot = longest["tpot"]["p50_ms"]
    return (
        f"At fp32, {ttft / tpot:.0f}x apart: {ttft:.0f} ms for a {prompt}-token prompt, "
        f"then {tpot:.2f} ms a token"
    )


def plot_arena_cost(data: dict, path: Path) -> None:
    """What the block allocator costs: absolute gather, then share of a step."""
    import matplotlib.pyplot as plt

    figure, (left, right) = plt.subplots(1, 2, figsize=(11.0, 4.2))
    scatter_range: list[float] = []
    share_labels: list[tuple[float, float, str, str]] = []

    for profile in data["precisions"]:
        precision = profile["precision"]
        colour = SERIES_COLOURS[precision]
        decode = sorted(profile["decode"], key=lambda row: row["cached_tokens"])
        xs = [row["cached_tokens"] for row in decode]
        scatter_range.extend(row["scatter_p50_ms"] for row in decode)

        left.plot(
            xs,
            [row["gather_p50_ms"] for row in decode],
            marker=SERIES_MARKERS[precision],
            markersize=5,
            linewidth=2,
            color=colour,
            label=precision,
        )
        ys = [row["arena_cost_pct"] for row in decode]
        right.plot(
            xs, ys, marker=SERIES_MARKERS[precision], markersize=5, linewidth=2, color=colour
        )
        share_labels.append((xs[-1], ys[-1], precision, colour))

    # No end labels on the left: the three lines coincide, which is the panel's point,
    # so three labels stacked on one place would obscure it. The legend carries
    # identity there instead.
    _style(
        left,
        xlabel="Cached tokens",
        ylabel="Gather (ms)",
        title="Gathering blocks into the graph's tensors",
    )
    _style(
        right,
        xlabel="Cached tokens",
        ylabel="Share of the decode step (%)",
        title="The same cost, as a share of the step",
    )
    left.legend(loc="upper left", fontsize=8, frameon=False)
    _label_ends(right, share_labels)
    # Without this the panel invites exactly the wrong reading: int4's share is lowest
    # because the step it is a share of is slowest, not because its gather is cheaper.
    right.annotate(
        "int4's share is lowest because its step is slowest,\nnot because its gather is cheaper",
        xy=(0.04, 0.86),
        xycoords="axes fraction",
        fontsize=8,
        color=INK_MUTED,
    )

    # One precision's longest step, named rather than taken from a flattened max, so
    # the quoted bandwidth belongs to a row somebody can find in the JSON.
    reference = data["precisions"][0]
    longest = max(reference["decode"], key=lambda row: row["cached_tokens"])
    # MB per ms is GB per s, so there is no factor of 1000 here.
    bandwidth = longest["cache_mb"] / longest["gather_p50_ms"]
    # Below the panels rather than inside one: the gather lines run corner to corner,
    # so there is no room in the axes that does not cross the data.
    figure.text(
        0.5,
        0.02,
        f"The gather is the same at every precision to within a few percent, because it "
        f"is pure memcpy: {longest['cache_mb']:.1f} MB in "
        f"{longest['gather_p50_ms']:.2f} ms is {bandwidth:.0f} GB/s, which is the rate "
        f"one thread of this host copies at.\nScatter is not plotted because it does not "
        f"move with the cache: it writes only the new token, "
        f"{min(scatter_range):.3f} to {max(scatter_range):.3f} ms at every length.",
        fontsize=8,
        color=INK_MUTED,
        ha="center",
    )

    figure.suptitle(
        "The block arena is accounting, not a speedup: this is what the accounting costs",
        fontsize=11,
        color=INK,
    )
    _save(figure, path, bottom=0.14)


def plot_chunked_prefill(data: dict, path: Path) -> None:
    """Chunk width against TTFT, indexed to one pass, and the logits each allocates."""
    import matplotlib.pyplot as plt

    prompt = max(row["prompt_tokens"] for row in data["precisions"][0]["prefill"])
    figure, (left, right) = plt.subplots(1, 2, figsize=(11.0, 4.2))

    # Widths come from the first precision and the rest are plotted against them, so a
    # precision measured at different widths would be visible as a short line rather
    # than silently redrawing the axis.
    widths = [row["chunk_tokens"] for row in _chunk_sweep(data["precisions"][0], prompt)]
    labels = ["one pass" if width == 0 else str(width) for width in widths]
    positions = list(range(len(widths)))
    ratio_labels: list[tuple[float, float, str, str]] = []

    for profile in data["precisions"]:
        precision = profile["precision"]
        rows = {row["chunk_tokens"]: row for row in _chunk_sweep(profile, prompt)}
        if 0 not in rows:
            LOGGER.warning("%s has no single-pass prefill to index against; skipping it", precision)
            continue
        single = rows[0]["ttft"]["p50_ms"]
        xs = [x for x, width in zip(positions, widths, strict=True) if width in rows]
        ys = [rows[width]["ttft"]["p50_ms"] / single for width in widths if width in rows]
        left.plot(
            xs,
            ys,
            marker=SERIES_MARKERS[precision],
            markersize=5,
            linewidth=2,
            color=SERIES_COLOURS[precision],
            label=precision,
        )
        ratio_labels.append((xs[-1], ys[-1], precision, SERIES_COLOURS[precision]))

    left.axhline(1.0, color=INK_MUTED, linestyle="--", linewidth=1)
    left.set_xticks(positions, labels)
    _style(
        left,
        xlabel="Prefill chunk width (tokens)",
        ylabel=f"TTFT relative to one pass over {prompt} tokens",
        title="Splitting the prefill is faster, not slower",
    )
    left.legend(loc="lower left", fontsize=8, frameon=False)
    _label_ends(left, ratio_labels)

    # One series, so one colour and no legend: the logits a width allocates are the
    # same whatever the weights are.
    rows = _chunk_sweep(data["precisions"][0], prompt)
    right.bar(
        positions,
        [row["peak_logits_mb"] for row in rows],
        width=0.62,
        color=SERIES_COLOURS["fp32"],
    )
    right.set_xticks(positions, labels)
    _style(
        right,
        xlabel="Prefill chunk width (tokens)",
        ylabel="Peak logits allocated (MB)",
        title="And it allocates less that nothing reads",
        label_room=False,
    )

    figure.suptitle(
        f"Chunked prefill over a {prompt}-token prompt: faster as well as smaller",
        fontsize=11,
        color=INK,
    )
    _save(figure, path)


def _save(figure: Any, path: Path, *, top: float = 0.94, bottom: float = 0.0) -> None:
    figure.tight_layout(rect=(0, bottom, 1, top))
    path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(path, dpi=FIGURE_DPI, facecolor="white")
    LOGGER.info("Wrote %s", path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("results/decode_profiles.json"),
        help="Measurements written by scripts/profile_decode.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("docs/img"),
        help="Where the figures are written",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        raise SystemExit(
            f"{args.input} is missing. Measure first:\n    python scripts/profile_decode.py"
        )

    try:
        import matplotlib
    except ImportError as error:  # pragma: no cover - depends on the environment
        raise SystemExit(
            "matplotlib is required to draw figures. Install it with:\n"
            '    pip install -e ".[bench]"'
        ) from error
    matplotlib.use("Agg")

    data = json.loads(args.input.read_text())
    if not data.get("precisions"):
        raise SystemExit(f"{args.input} records no precisions, so there is nothing to draw")
    unknown = {p["precision"] for p in data["precisions"]} - set(SERIES_COLOURS)
    if unknown:
        raise SystemExit(
            f"no colour is assigned to {sorted(unknown)}. A precision keeps one colour "
            f"across every figure, so add it to SERIES_COLOURS rather than letting "
            f"matplotlib cycle one."
        )

    plot_phases(data, args.output_dir / "decoder_phases.png")
    plot_arena_cost(data, args.output_dir / "arena_cost.png")
    plot_chunked_prefill(data, args.output_dir / "chunked_prefill.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
